# Generated by Django 4.0.4 on 2022-05-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfiletwo',
            new_name='UserUpdateForm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
