# Generated by Django 4.0.4 on 2022-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_userprofiletwo_userupdateform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUpdateForm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
