# Generated by Django 4.0.4 on 2022-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('category', models.CharField(choices=[('FS', 'FullStack'), ('DS', 'DataScience'), ('AWS', 'AmazonWebService')], default='FS', max_length=20)),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'Publish')], default='1', max_length=20)),
            ],
        ),
    ]
