# Generated by Django 4.0.4 on 2022-05-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostcreate',
            old_name='Image',
            new_name='image',
        ),
    ]
