# Generated by Django 4.0.4 on 2022-05-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_userpostcreate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostcreate',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
